/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const NewMachineFields = IDL.Record({ 'name' : IDL.Text });
export const NewOperatorFields = IDL.Record({ 'name' : IDL.Text });
export const NewProductFields = IDL.Record({
  'cycleTime' : IDL.Nat,
  'name' : IDL.Text,
  'loadingTime' : IDL.Nat,
  'unloadingTime' : IDL.Nat,
  'piecesPerCycle' : IDL.Nat,
});
export const MachineId = IDL.Nat;
export const OperatorId = IDL.Nat;
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EntryId = IDL.Nat;
export const Machine = IDL.Record({ 'id' : MachineId, 'name' : IDL.Text });
export const Operator = IDL.Record({ 'id' : OperatorId, 'name' : IDL.Text });
export const RuntimeType = IDL.Record({
  'hours' : IDL.Nat,
  'minutes' : IDL.Nat,
  'seconds' : IDL.Nat,
});
export const TimeInterval = IDL.Record({
  'hours' : IDL.Nat,
  'minutes' : IDL.Nat,
  'seconds' : IDL.Nat,
});
export const ProductionEntry = IDL.Record({
  'id' : EntryId,
  'cycleTime' : IDL.Record({ 'minutes' : IDL.Nat, 'seconds' : IDL.Nat }),
  'punchOut' : IDL.Int,
  'productId' : ProductId,
  'downtimeTime' : IDL.Record({ 'minutes' : IDL.Nat, 'seconds' : IDL.Nat }),
  'totalRunTime' : RuntimeType,
  'punchIn' : IDL.Int,
  'operatorId' : OperatorId,
  'dutyTime' : TimeInterval,
  'timestamp' : IDL.Int,
  'twelveHourTarget' : IDL.Nat,
  'downtimeReason' : IDL.Text,
  'tenHourTarget' : IDL.Nat,
  'numberOfPartsProduced' : IDL.Nat,
  'quantityProduced' : IDL.Nat,
  'machineId' : MachineId,
  'totalOperatorHours' : TimeInterval,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'cycleTime' : IDL.Nat,
  'name' : IDL.Text,
  'loadingTime' : IDL.Nat,
  'unloadingTime' : IDL.Nat,
  'piecesPerCycle' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMachine' : IDL.Func([NewMachineFields], [], []),
  'addOperator' : IDL.Func([NewOperatorFields], [], []),
  'addProduct' : IDL.Func([NewProductFields], [], []),
  'addProductionEntry' : IDL.Func(
      [
        MachineId,
        OperatorId,
        ProductId,
        IDL.Record({ 'minutes' : IDL.Nat, 'seconds' : IDL.Nat }),
        IDL.Nat,
        IDL.Text,
        IDL.Record({ 'minutes' : IDL.Nat, 'seconds' : IDL.Nat }),
        IDL.Int,
        IDL.Int,
        IDL.Opt(IDL.Int),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMachine' : IDL.Func([MachineId], [], []),
  'deleteOperator' : IDL.Func([OperatorId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deleteProductionEntry' : IDL.Func([EntryId], [], []),
  'getAllMachines' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
  'getAllMachinesSortedByName' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
  'getAllOperators' : IDL.Func([], [IDL.Vec(Operator)], ['query']),
  'getAllOperatorsSortedByName' : IDL.Func([], [IDL.Vec(Operator)], ['query']),
  'getAllProductionEntries' : IDL.Func(
      [],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProductsSortedByLoadingTime' : IDL.Func(
      [],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllProductsSortedByName' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProductsSortedByPiecesPerCycle' : IDL.Func(
      [],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllProductsSortedByUnloadingTime' : IDL.Func(
      [],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllProductsUnsorted' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProductionEntriesByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getProductionEntriesByOperator' : IDL.Func(
      [OperatorId],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getProductionEntriesByProduct' : IDL.Func(
      [ProductId],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getSortedProductionEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getSortedProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMachine' : IDL.Func([MachineId, IDL.Text], [], []),
  'updateOperator' : IDL.Func([OperatorId, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const NewMachineFields = IDL.Record({ 'name' : IDL.Text });
  const NewOperatorFields = IDL.Record({ 'name' : IDL.Text });
  const NewProductFields = IDL.Record({
    'cycleTime' : IDL.Nat,
    'name' : IDL.Text,
    'loadingTime' : IDL.Nat,
    'unloadingTime' : IDL.Nat,
    'piecesPerCycle' : IDL.Nat,
  });
  const MachineId = IDL.Nat;
  const OperatorId = IDL.Nat;
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EntryId = IDL.Nat;
  const Machine = IDL.Record({ 'id' : MachineId, 'name' : IDL.Text });
  const Operator = IDL.Record({ 'id' : OperatorId, 'name' : IDL.Text });
  const RuntimeType = IDL.Record({
    'hours' : IDL.Nat,
    'minutes' : IDL.Nat,
    'seconds' : IDL.Nat,
  });
  const TimeInterval = IDL.Record({
    'hours' : IDL.Nat,
    'minutes' : IDL.Nat,
    'seconds' : IDL.Nat,
  });
  const ProductionEntry = IDL.Record({
    'id' : EntryId,
    'cycleTime' : IDL.Record({ 'minutes' : IDL.Nat, 'seconds' : IDL.Nat }),
    'punchOut' : IDL.Int,
    'productId' : ProductId,
    'downtimeTime' : IDL.Record({ 'minutes' : IDL.Nat, 'seconds' : IDL.Nat }),
    'totalRunTime' : RuntimeType,
    'punchIn' : IDL.Int,
    'operatorId' : OperatorId,
    'dutyTime' : TimeInterval,
    'timestamp' : IDL.Int,
    'twelveHourTarget' : IDL.Nat,
    'downtimeReason' : IDL.Text,
    'tenHourTarget' : IDL.Nat,
    'numberOfPartsProduced' : IDL.Nat,
    'quantityProduced' : IDL.Nat,
    'machineId' : MachineId,
    'totalOperatorHours' : TimeInterval,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'cycleTime' : IDL.Nat,
    'name' : IDL.Text,
    'loadingTime' : IDL.Nat,
    'unloadingTime' : IDL.Nat,
    'piecesPerCycle' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMachine' : IDL.Func([NewMachineFields], [], []),
    'addOperator' : IDL.Func([NewOperatorFields], [], []),
    'addProduct' : IDL.Func([NewProductFields], [], []),
    'addProductionEntry' : IDL.Func(
        [
          MachineId,
          OperatorId,
          ProductId,
          IDL.Record({ 'minutes' : IDL.Nat, 'seconds' : IDL.Nat }),
          IDL.Nat,
          IDL.Text,
          IDL.Record({ 'minutes' : IDL.Nat, 'seconds' : IDL.Nat }),
          IDL.Int,
          IDL.Int,
          IDL.Opt(IDL.Int),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMachine' : IDL.Func([MachineId], [], []),
    'deleteOperator' : IDL.Func([OperatorId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deleteProductionEntry' : IDL.Func([EntryId], [], []),
    'getAllMachines' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
    'getAllMachinesSortedByName' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
    'getAllOperators' : IDL.Func([], [IDL.Vec(Operator)], ['query']),
    'getAllOperatorsSortedByName' : IDL.Func(
        [],
        [IDL.Vec(Operator)],
        ['query'],
      ),
    'getAllProductionEntries' : IDL.Func(
        [],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProductsSortedByLoadingTime' : IDL.Func(
        [],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllProductsSortedByName' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProductsSortedByPiecesPerCycle' : IDL.Func(
        [],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllProductsSortedByUnloadingTime' : IDL.Func(
        [],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllProductsUnsorted' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProductionEntriesByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getProductionEntriesByOperator' : IDL.Func(
        [OperatorId],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getProductionEntriesByProduct' : IDL.Func(
        [ProductId],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getSortedProductionEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getSortedProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMachine' : IDL.Func([MachineId, IDL.Text], [], []),
    'updateOperator' : IDL.Func([OperatorId, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };