/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EntryId = bigint;
export interface Machine { 'id' : MachineId, 'name' : string }
export type MachineId = bigint;
export interface Operator { 'id' : OperatorId, 'name' : string }
export type OperatorId = bigint;
export interface Product {
  'id' : ProductId,
  'cycleTime' : bigint,
  'name' : string,
  'loadingTime' : bigint,
  'unloadingTime' : bigint,
  'piecesPerCycle' : bigint,
}
export type ProductId = bigint;
export interface ProductionEntry {
  'id' : EntryId,
  'cycleTime' : { 'minutes' : bigint, 'seconds' : bigint },
  'punchOut' : bigint,
  'productId' : ProductId,
  'downtimeTime' : { 'minutes' : bigint, 'seconds' : bigint },
  'totalRunTime' : RuntimeType,
  'punchIn' : bigint,
  'operatorId' : OperatorId,
  'dutyTime' : TimeInterval,
  'timestamp' : bigint,
  'twelveHourTarget' : bigint,
  'downtimeReason' : string,
  'tenHourTarget' : bigint,
  'numberOfPartsProduced' : bigint,
  'quantityProduced' : bigint,
  'machineId' : MachineId,
  'totalOperatorHours' : TimeInterval,
}
export interface RuntimeType {
  'hours' : bigint,
  'minutes' : bigint,
  'seconds' : bigint,
}
export interface TimeInterval {
  'hours' : bigint,
  'minutes' : bigint,
  'seconds' : bigint,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProductionEntry' : ActorMethod<
    [
      MachineId,
      OperatorId,
      ProductId,
      { 'minutes' : bigint, 'seconds' : bigint },
      bigint,
      string,
      { 'minutes' : bigint, 'seconds' : bigint },
      bigint,
      bigint,
      [] | [bigint],
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMachine' : ActorMethod<[string], MachineId>,
  'createOperator' : ActorMethod<[string], OperatorId>,
  'createProduct' : ActorMethod<
    [string, bigint, bigint, bigint, bigint],
    ProductId
  >,
  'deleteMachine' : ActorMethod<[MachineId], undefined>,
  'deleteOperator' : ActorMethod<[OperatorId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteProductionEntry' : ActorMethod<[EntryId], undefined>,
  'getAllMachines' : ActorMethod<[], Array<Machine>>,
  'getAllMachinesSortedByName' : ActorMethod<[], Array<Machine>>,
  'getAllOperators' : ActorMethod<[], Array<Operator>>,
  'getAllOperatorsSortedByName' : ActorMethod<[], Array<Operator>>,
  'getAllProductionEntries' : ActorMethod<[], Array<ProductionEntry>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProductsSortedByLoadingTime' : ActorMethod<[], Array<Product>>,
  'getAllProductsSortedByName' : ActorMethod<[], Array<Product>>,
  'getAllProductsSortedByPiecesPerCycle' : ActorMethod<[], Array<Product>>,
  'getAllProductsSortedByUnloadingTime' : ActorMethod<[], Array<Product>>,
  'getAllProductsUnsorted' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProductionEntriesByDateRange' : ActorMethod<
    [bigint, bigint],
    Array<ProductionEntry>
  >,
  'getProductionEntriesByOperator' : ActorMethod<
    [OperatorId],
    Array<ProductionEntry>
  >,
  'getProductionEntriesByProduct' : ActorMethod<
    [ProductId],
    Array<ProductionEntry>
  >,
  'getSortedProductionEntries' : ActorMethod<[string], Array<ProductionEntry>>,
  'getSortedProducts' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMachine' : ActorMethod<[MachineId, string], undefined>,
  'updateOperator' : ActorMethod<[OperatorId, string], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, bigint, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];